$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: lightgbm-env
image: mcr.microsoft.com/azureml/openmpi3.1.2-ubuntu18.04
conda_file: conda-yaml/lightgbm-env.yml
description: LightGBM environments