$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue
model: azureml:lgb-custom-model@latest
app_insights_enabled: true
code_configuration:
  code: ./src
  scoring_script: score.py
environment: azureml:lightgbm-env-inference@latest
instance_type: Standard_F2s_v2
instance_count: 1