name: endpoints-testing
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - outer-loop/*

jobs:
  build:
    name: "Endpoints Testing"
    runs-on: "ubuntu-18.04"
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: echo
      run: az --version
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh ${{secrets.RESOURCE}} ${{secrets.WORKSPACE}} ${{secrets.LOCATION}}
      working-directory: admin/cli
    - name: Endpoints Testing
      run: |
        az ml online-endpoint invoke --name lgb-endpoint-stage --request-file ./endpoints_testing/sample_request.json
        az ml online-endpoint invoke --name lgb-endpoint-prod --request-file ./endpoints_testing/sample_request.json
      working-directory: outer-loop