name: safe-rollout
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - outer-loop/*

jobs:
  build:
    name: "Safe Rollout"
    runs-on: "ubuntu-18.04"
    steps:
    - name: check out repo
      uses: actions/checkout@v2
    - name: echo
      run: az --version
    - name: azure login
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZ_CREDS}}
    - name: setup
      run: bash setup.sh ${{secrets.RESOURCE}} ${{secrets.WORKSPACE}} ${{secrets.LOCATION}}
      working-directory: admin/cli
    - name: Allocate Traffic to GREEN
      run:  bash ./allocate-traffic.sh
      working-directory: outer-loop/safe_rollout